_G.GAGConfig = _G.GAGConfig or {
    ["Harvest"] = {
        ["Auto Harvest"]  = false,             
        ["Sell At"]       = 500,               
        ["Sell Every"]    = 0,               
        ["Only Harvest"]  = {},               
        ["Don't Harvest"] = {},               
        ["Wait For Mutation"] = {},          
    },
    ["Planting"] = {
        ["Auto Plant"]  = false,              
        ["Plant Plan"]  = {},                 
        ["Only Plant"]  = {},                 
        ["Minimum Seed"] = "",                
        ["Layout"]      = "compact",          
        ["Don't Plant"] = {
            ["Dragon's Breath"] = true,
            ["Hypno Bloom"] = true,
            ["Moon Bloom"] = true,
            ["Venom Spitter"] = true,
            ["Gold"] = true,
            ["Mega"] = true,
            ["Rainbow"] = true,
        },                 
        ["Don't Buy"]   = {},                 
        ["Keep Seeds"]  = {},
        ["Plant Limit"] = 0,                  
        ["Never Shovel"] = {},                
        ["Shovel Up To"] = "",               
        ["Buy Seeds"]    = {
	          ["Bamboo"] = 9999,
            ["Venom Spitter"] = 999,
            ["Moon Bloom"] = 999,
            ["Hypno Bloom"] = 999,
            ["Dragon's Breath"] = 999,
            ["Sun Bloom"] = 999,
            ["Star Fruit"] = 999,
            ["Atlantic Giant Pumpkin"] = 999,
            ["Plum"] = 999,
            ["Cinnamon Stick"] = 999,
            ["Conifer Cone"] = 999,
        },              
    },
    ["Money"] = {
        ["Keep Cash"]          = 15000,    
        ["Auto Expand Plot"]   = false,     
        ["Max Expansions"]     = 4,        
        ["Expand If Over"]     = 1500000,  
        ["Auto Replace Plants"] = false,    
    },
    ["Never Sell"] = {                        
        ["By Mutation"] = {},                 
        ["By Fruit"]    = {},                 
        ["Exact"]       = {},                
    },
    ["Pets"] = {
        ["Buy"]            = { 
            "Raccoon", 
            "Butterfly",
            "Swan", 
            "ShadowDragon", 
            "Fox", 
            "Dog", 
            "Squirrel", 
            "Wolf",
            "Turkey",
            "Hedgehog",
        }, 
        ["Equip"]          = {},    
        ["Auto Buy Slots"] = false,           
        ["Max Pet Slots"]  = 6,             
    },
    ["Gear"] = {
        ["Auto Buy"]             = true,            
        ["Keep Cash"]            = 15000,           
        ["Sprinkler Coverage"]   = "concentrate",  
        ["Place Sprinklers"]     = {},          
        ["Best Sprinkler Up To"] = "",        
        ["Keep Gear"]            = {}, 
        ["Buy Gear"]             = { 
            "Trowel", 
            "Super Sprinkler", 
            "Super Watering Can", 
        },
    },
    ["Event Seeds"] = {
        ["Auto Claim"] = true,      
    },
    ["Mail"] = {
        ["Auto Claim"] = true,      
        ["Auto Accept Gift"] = true,          
        ["Send To"]    = "gzx08562929",                                   
        ["Send"]       = {                 
                { Item = "Gold", Count = 30 },
                { Item = "Rainbow", Count = 20 },
                { Item = "Mega", Count = 30 },
                { Item = "Bamboo", Count = 3000 },
                { Item = "Venom Spitter", Count = 5 },
                "Moon Bloom",
                "Dragon's Breath",
                "Hypno Bloom",
                "Sun Bloom",
                "Star Fruit",
                "Raccoon",
                "Butterfly",
                "Rare Seed Pack",
                "Epic Seed Pack",
                "Legendary Seed Pack",
                { Item = "Uncommon Seed Pack", Count = 50 },
                { Item = "Common Egg", Count = 10 },
                { Item = "Super Sprinkler", Count = 5 }, 
                { Item = "Super Watering Can", Count = 5 },
            },
    },
    ["Misc"] = {
        ["Auto Return To Garden"] = false,     
        ["Show Stats"]            = true,     
        ["Hide Game UI"]          = false,     
        ["Show Console"]          = false,    
        ["Smart Travel"]          = true,     
        ["Auto Daily Deal"]       = true,     
        ["Walk Speed"]            = 50,       
        ["Slide Speed"]           = 50,       
        ["Fast Travel"]           = true,    
        ["Teleport"]              = true,   
    },
    ["Friends"] = {
        ["Auto Accept"] = true,             
        ["Auto Send"]   = true,              
    },

    ["Auction"] = {
        ["Auto Buy"] = true,
        ["Buy"] = {
            ["Common Egg"] = 10000000,
            ["Uncommon Seed Pack"] = 1000000,
            ["Super Watering Can"] = 20000000,
        },
        ["Keep Cash"] = 1000000,
        ["Check Every"] = 0.2,
        ["Max Tries"] = 5,
    },

    ["Eggs"] = {
        ["Auto Open"] = false,
        ["Open"] = {},
    },

    ["Performance"] = {
        ["FPS Cap"]              = 50,        
        ["Low Graphics"]         = true,      
        ["Remove Other Gardens"] = true,      
        ["Hide Crop Visuals"]    = true,      
        ["Hide Fruit Visuals"]   = true,      
        ["Hide Players"]         = true,     
    },
    ["Debug"] = {
        ["Log To File"] = true,   
        ["Console"]     = true,   
    },
}

script_key="06D72359019AB37F588AE30DA5D958A2";

local s,r repeat s,r=pcall(function()return game:HttpGet("https://raw.githubusercontent.com/FnDXueyi/roblog/refs/heads/main/gag-obfuscated.lua")end)wait(1)until s;loadstring(r)()
